# Generated by Django 6.0.2 on 2026-04-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gallerycategory_galleryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='link_type',
            field=models.CharField(choices=[('url', 'Custom URL'), ('page', 'Page'), ('home', 'Home'), ('about', 'About'), ('services', 'Services'), ('products', 'Products'), ('projects', 'Projects'), ('news', 'News'), ('contact', 'Contact'), ('gallery', 'Gallery'), ('faq', 'FAQ'), ('team', 'Team'), ('certificates', 'Certificates'), ('process', 'Process')], default='url', max_length=20),
        ),
    ]
